- name: demo-playbook
  hosts: qa
  become: 'yes'
  become_user: ansible-client
  tasks:
    #- name: create the directory on the client machine
    #  shell: echo admin | sudo -S mkdir /opt/ci-cd-files

    - name: change the directory permissions
      shell: echo admin | sudo -S chmod 777 /opt/ci-cd-files

    - name: copy the files from ansible server to client machines
      copy: src=/opt/ dest=/opt/ci-cd-files 
